[workspace]
members  = ["crates/pdf-viewer", "examples/sample-wasm-bindgen"]
resolver = "2"

[workspace.dependencies]
pdf-viewer = { path = "crates/pdf-viewer" }

js-sys       = "0.3.72"
wasm-bindgen = "0.2.95"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
