[package]
edition = "2021"
name    = "sample-wasm-bindgen"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
pdf-viewer = { workspace = true }

js-sys       = { workspace = true }
wasm-bindgen = { workspace = true }
